name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/test
        
      - name: Test with the Go CLI
        run: go test ./...

      - name: Force Failure
        run: (exit 0)